export const SUBMIT_SEARCH = 'SUBMIT_SEARCH';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const PROCESS_SEARCH_RESULTS = 'PROCESS_SEARCH_RESULTS';
export const SET_VIEW = 'SET_VIEW'
export const UPDATE_ZIP_CODE = 'UPDATE_ZIP_CODE'