export const SUBMIT_SEARCH = 'SUBMIT_SEARCH';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const PROCESS_EVENTBRITE_RESULTS = 'PROCESS_EVENTBRITE_RESULTS';
export const PROCESS_YELP_RESULTS = 'PROCESS_YELP_RESULTS'


export const SET_VIEW = 'SET_VIEW'
export const UPDATE_ZIP_CODE = 'UPDATE_ZIP_CODE'