let mockdata = {
  name: "The Waterfront Venice",
  imgurl: "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F64648119%2F172016761098%2F1%2Foriginal.20190629-205819?h=200&w=450&auto=compress&rect=0%2C212%2C1000%2C500&s=763656b58bdff7f86cd7de3d09b40c34",
  starttime: "2019-08-31T12:00:00",
  endtime: "2019-08-31T18:00:00",
  description: "LABOR DAY WEEKEND • SOUTHERN CALIFORNIA • ALL AGES FAMILY EVENT\nAdamari Empire presents the 4th Annual Roots & Yam Jerk Food Fest. Bring the family out to enjoy rare juicy delicious JERK chicken, JERK shrimp, JERK fish all sided with your choice of JERK pineapple, jasmine rice, JERK beans and all sort of other tasty food from the Caribbean. Enjoy the summer weather fused with authentic LIVE BANDS and DJs from the islands!!!\nJERK FEST is a cultural awareness festival that brings together thousands of friends and families for the ultimate Caribbean experience in Southern California. Bring the family out for a fun filled day of Live Music, Exotic Food & Drinks, Beautiful Carnival Ladies, Dancing, Organic Farmer's Market and Caribbean Animals from around the world. Learn about our culture and keep in touch with your roots!\n\n========== SATURDAY • AUGUST 31, 2019 • FOOD FEST ==========\nCome out to enjoy and discover the best Jerk & Caribbean food Southern California has to offer! Featuring delicious authentic dishes from chefs and cooks straight from the Islands.  Mix and mingle with others who also love Caribbean food and culture.  Enjoy your tasty food along with melodic sounds from our top class DJs and soundsystems.\nFREE ADMISSION on Saturday, August 31, 2019 ONLY with reserved ticket. Limited capacity.  First come, first reserve.\n\n========== SUNDAY • SEPTEMBER 1, 2019 • MUSIC FEST ==========\nOn Labor Day Sunday, don't miss your chance to experience live performances from top international acts from around the world.  It's the music festival portion of Jerk Fest featuring Live performances by Capleton, Johnny Osbourne, Live Wyaa Band, Firgo Digital and many more to be announced.  Come enjoy Reggae, Dancehall, Soca, Punta, Afrobeats and Reggaeton artists from around the world.  Music fest tickets start at $50.  Children Ages 7 & Under are FREE!!! Children ages 8-17 are half price at the gate only.  More information can be found here: http://www.jerkfoodfest.com\nLive performances by:••• CAPLETON •••••• KONSHENS •••••• JOHNNY OSBOURNE •••••• JAHMIEL •••••• TIMAYA •••••• OLATUNJI •••••• LIVE WYAA BAND •••\n\nFood & Beverages are sold separately.",
  longlat: ["-118.48071340000001","33.995139",],
  isFree: false,
  website: 'https://www.eventbrite.com/e/stoked-on-the-beach-tickets-65721692351',
  address: '205 Ocean Front Walk',
  price: '2.64',
  category:'music',
}